INSERT INTO `book_db` . `genres` (`name`) VALUES ('fantasy');
INSERT INTO `book_db` . `genres` (`name`) VALUES ('adventure');
INSERT INTO `book_db` . `genres` (`name`) VALUES ('romance');
INSERT INTO `book_db` . `genres` (`name`) VALUES ('contemporary');
INSERT INTO `book_db` . `genres` (`name`) VALUES ('dystopian');
INSERT INTO `book_db` . `genres` (`name`) VALUES ('mystery');
INSERT INTO `book_db` . `genres` (`name`) VALUES ('horror');
INSERT INTO `book_db` . `genres` (`name`) VALUES ('thriller');
INSERT INTO `book_db` . `genres` (`name`) VALUES ('paranormal');
INSERT INTO `book_db` . `genres` (`name`) VALUES ('historical fiction');
INSERT INTO `book_db` . `genres` (`name`) VALUES ('science fiction');
INSERT INTO `book_db` . `genres` (`name`) VALUES ('childrens');
INSERT INTO `book_db` . `genres` (`name`) VALUES ('memoir');
INSERT INTO `book_db` . `genres` (`name`) VALUES ('cooking');
INSERT INTO `book_db` . `genres` (`name`) VALUES ('art');
INSERT INTO `book_db` . `genres` (`name`) VALUES ('personal');
INSERT INTO `book_db` . `genres` (`name`) VALUES ('development');
INSERT INTO `book_db` . `genres` (`name`) VALUES ('motivational');
INSERT INTO `book_db` . `genres` (`name`) VALUES ('health');
INSERT INTO `book_db` . `genres` (`name`) VALUES ('travel');
INSERT INTO `book_db` . `genres` (`name`) VALUES ('families and relationships');
INSERT INTO `book_db` . `genres` (`name`) VALUES ('humor');
